[package]
name = "open_cdd"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
tokio = { version = "1.12", features = ["full"] }
serde_json = "1.0"
serde = "1.0"
futures = "0.3"