[package]
name = "open_cdd"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12", features = ["full"] }
serde = "1.0"
futures = "0.3"
futures-locks = "0.6"
chrono = "0.4"
ron = "0.7"
lazy_static = "1.4"
regex = "1.5"

[dependencies.serenity]
version = "0.10"
features = ["unstable_discord_api"]