name: Rustdoc

on:
  workflow_dispatch:
    
  push:
    branches: [ docs ]
  pull_request:
    branches: [ docs ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: ./docs

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build documentation
      - run: cargo doc --verbose
